#ifndef OPARTICLEMODIFIER_H__
#define OPARTICLEMODIFIER_H__

#define Oparticlemodifier 1000004

enum
{
	OPARTICLEMODIFIER_CODE = 400,
	OPARTICLEMODIFIER_NUMPY,

	OPARTICLEMODIFIER_OPENEDITOR = 2001
};

#endif // OPARTICLEMODIFIER_H__
