CONTAINER Oxpmodifier
{
	NAME Oxpmodifier;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		SCALE_V;
		GROUP
		{
		  LAYOUTGROUP; COLUMNS 3;

		  GROUP
		  {
		    BOOL OXPMODIFIER_POSITION { }
		    BOOL OXPMODIFIER_VELOCITY { }
		    BOOL OXPMODIFIER_TIME { }
		    BOOL OXPMODIFIER_LIFE { }
		    BOOL OXPMODIFIER_COLOR { }
		    BOOL OXPMODIFIER_RADIUS { }
		    BOOL OXPMODIFIER_MASS { }
		    BOOL OXPMODIFIER_SPEED { }
		  }

		  GROUP
		  {
		    BOOL OXPMODIFIER_GROUPID { }
		    BOOL OXPMODIFIER_ID { }
		    BOOL OXPMODIFIER_DENSITY { }
		    BOOL OXPMODIFIER_DISPLAY { }
		    BOOL OXPMODIFIER_MATRIX { }
		    BOOL OXPMODIFIER_ROTATION { }
		    BOOL OXPMODIFIER_DISTANCE { }
		  }

		  GROUP
		  {
		    BOOL OXPMODIFIER_SPIN { }
		    BOOL OXPMODIFIER_TEMPERATURE { }
		    BOOL OXPMODIFIER_FUEL { }
		    BOOL OXPMODIFIER_FIRE { }
		    BOOL OXPMODIFIER_SMOKE { }
		    BOOL OXPMODIFIER_EXPANSION { }
		    BOOL OXPMODIFIER_UVW { }
		  }
		}

		SEPARATOR { LINE; }

		STRING OXPMODIFIER_CODE
		{
		  CUSTOMGUI MULTISTRING;
		  PYTHON;
		  SCALE_V;
		}

		BUTTON OXPMODIFIER_OPENEDITOR { }
	}    
}
