#ifndef OXPMODIFIER_H__
#define OXPMODIFIER_H__

#define Oxpmodifier 1000005

enum
{
	OXPMODIFIER_CODE = 400,
    OXPMODIFIER_NUMPY,

	OXPMODIFIER_OPENEDITOR = 2001,
    OXPMODIFIER_FRAME,
    
    OXPMODIFIER_POSITION = 3001,
    OXPMODIFIER_VELOCITY,
    OXPMODIFIER_TIME,
    OXPMODIFIER_LIFE,
    OXPMODIFIER_COLOR,
    OXPMODIFIER_RADIUS,
    OXPMODIFIER_MASS,
    OXPMODIFIER_SPEED,
    OXPMODIFIER_GROUPID,
    OXPMODIFIER_ID,
    OXPMODIFIER_DENSITY,

    OXPMODIFIER_DISPLAY,
    OXPMODIFIER_MATRIX,
    OXPMODIFIER_ROTATION,
    OXPMODIFIER_DISTANCE,
    OXPMODIFIER_SPIN,
    OXPMODIFIER_TEMPERATURE,
    OXPMODIFIER_FUEL,
    OXPMODIFIER_FIRE,
    OXPMODIFIER_SMOKE,
    OXPMODIFIER_EXPANSION,
    OXPMODIFIER_UVW
};

#endif // OXPMODIFIER_H__
